train:
  _target_: src.datasets.SourceSeparationDataset
  part: "train"
  data_dir: "/Users/timurkin/Downloads/dla_dataset"
val:
  _target_: src.datasets.SourceSeparationDataset
  part: "val"
  data_dir: "/Users/timurkin/Downloads/dla_dataset"