train:
  _target_: src.datasets.SourceSeparationDataset
  part: "train"
  data_dir: "/home/admin/dla_dataset"
val:
  _target_: src.datasets.SourceSeparationDataset
  part: "val"
  data_dir: "/home/admin/dla_dataset"
