_target_: src.logger.WandBWriter
project_name: "source_separation"
entity: null
run_name: "train_TasNet_batch=8_lr=1e-3"
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
